services:
  cubesatsim-aprs-parser:
    image: ${REGISTRY}/cubesatsim-aprs-parser-parser:main
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    entrypoint: ["./run-parser.sh"]

  cubesatsim-aprs-gauges:
    image: ${REGISTRY}/cubesatsim-aprs-parser-gauges:main
    restart: unless-stopped
    devices:
      - /dev/i2c-1
      - /dev/i2c-20
      - /dev/i2c-21
    privileged: true
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    entrypoint: ["./run-gauges.sh"]

  cubesatsim-aprs-buttons:
    image: ${REGISTRY}/cubesatsim-aprs-parser-buttons:main
    restart: unless-stopped
    devices:
      - /dev/gpiomem
    privileged: true
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    entrypoint: ["./run-buttons.sh"]

  cubesatsim-aprs-visualisation:
    image: ${REGISTRY}/cubesatsim-aprs-parser-visualisation:main
    restart: unless-stopped
    ports:
      - "80:80"

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
